sudo: required
services:
  - docker

before_install:
  - docker build -t pranavbhosale/react-test -f ./client/Dockerfile.dev ./client
  # - docker build <other containers> 

script:
  - docker run pranavbhosale/react-test npm test -- --coverage

after_sucess:
  - docker build -t pranavbhosale/multi-client ./client 
  - docker build -t pranavbhosale/multi-nginx ./nginx
  - docker build -t pranavbhosale/multi-server ./server
  - docker build -t pranavbhosale/multi-worker ./worker  
