sudo: required
language: node_js
services:
  - docker

before_install:
  - echo "before install complete"
  # - docker build -t pranavbhosale25/react-test -f ./client/Dockerfile.dev ./client
  # - docker build <other containers> 

script:
  - echo "script complete"
  # - docker run pranavbhosale25/react-test npm test -- --coverage

after_sucess:
  - docker build -t pranavbhosale25/multi-client ./client 
  - docker build -t pranavbhosale25/multi-nginx ./nginx
  - docker build -t pranavbhosale25/multi-server ./server
  - docker build -t pranavbhosale25/multi-worker ./worker  
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take images and push them to docker hub
  - docker push pranavbhosale25/multi-client
  - docker push pranavbhosale25/multi-nginx
  - docker push pranavbhosale25/multi-server
  - docker push pranavbhosale25/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'multi-docker'
  env: 'Multi-docker-env-2-env'
  bucket_name: 'elasticbeanstalk-us-west-2-800907137860'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  skip_cleanup: true